import type { Metadata } from "next";
import "./globals.scss";
import {Inter} from "next/font/google";
import Header from "@/components/header/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Next.js | Test project",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <div className='app-wrapper'>
                    <Header />
                    {children}
                </div>
            </body>
        </html>
    );
}
